# Generated by Django 4.1 on 2022-08-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='desc',
            field=models.CharField(default='ركون خاطئ', max_length=50),
        ),
    ]
